package com.claudehud.one.mobile

// AUTO-GENERATED by scripts/generate-mobile-hud-protocol.mjs. Do not edit manually.
object MobileHudProtocol {
    const val PROTOCOL_VERSION: Int = 1
    const val SCHEMA_VERSION: Int = 1
    const val TRUSTED_VIEW_PRIVACY_LEVEL: String = "trustedAppView"
    const val NOTIFICATION_SENSITIVITY: String = "low"
    const val MOBILE_EXECUTION_ROLE: String = "controlPlaneOnly"
    const val RAW_TRANSCRIPT_POLICY: String = "pcOnly"
    const val RAW_TOOL_DATA_POLICY: String = "pcOnly"
    const val TERMINAL_JUMP: Boolean = false
    const val APPROVAL_ACTIONS: Boolean = false
    const val QUESTION_ACTIONS: Boolean = false
    const val TRANSPORT: String = "wssSpkiPinning"
    const val DEVICE_IDENTITY: String = "pairedDevicePublicKey"
    const val INTENT_AUTH: String = "signedIntentWithNonceTtlBodyHash"
    const val DEVICE_ID_IS_CREDENTIAL: Boolean = false

    val DENIED_JSON_KEYS: Set<String> = setOf(
        "transcriptPath",
        "projectDir",
        "cwd",
        "terminal",
        "intentId",
        "allowedIntents",
        "nonce",
        "rawInput",
        "rawOutput",
        "toolInput",
        "toolResult",
        "wtSession",
        "windowTitleHint",
        "bridgeProcessId"
    )
}
