// AUTO-GENERATED by scripts/generate-mobile-hud-protocol.mjs. Do not edit manually.

export const MOBILE_HUD_PROTOCOL = {
  "protocolVersion": 1,
  "schemaVersion": 1,
  "trustedViewPrivacyLevel": "trustedAppView",
  "notificationSensitivity": "low",
  "mobileExecutionRole": "controlPlaneOnly",
  "rawTranscriptPolicy": "pcOnly",
  "rawToolDataPolicy": "pcOnly",
  "terminalJump": false,
  "approvalActions": false,
  "questionActions": false,
  "transport": "wssSpkiPinning",
  "deviceIdentity": "pairedDevicePublicKey",
  "intentAuth": "signedIntentWithNonceTtlBodyHash",
  "deviceIdIsCredential": false
} as const

export const MOBILE_HUD_DENIED_JSON_KEYS = [
  "transcriptPath",
  "projectDir",
  "cwd",
  "terminal",
  "intentId",
  "allowedIntents",
  "nonce",
  "rawInput",
  "rawOutput",
  "toolInput",
  "toolResult",
  "wtSession",
  "windowTitleHint",
  "bridgeProcessId"
] as const

export const MOBILE_HUD_DENIED_TEXT_MARKERS = [
  "transcript_path",
  "project_dir",
  "tool input",
  "tool result",
  "raw prompt",
  "raw output"
] as const

export type MobileHudProtocolVersion = typeof MOBILE_HUD_PROTOCOL.protocolVersion
