import type { DisplayItemDefinition, DisplayItemRegistry, HudDisplayItemId } from './types'

const item = (definition: DisplayItemDefinition): DisplayItemDefinition => definition

export const DISPLAY_ITEM_REGISTRY: DisplayItemRegistry = {
  model: item({
    id: 'model',
    label: 'Model',
    category: 'core',
    kind: 'part',
    fieldKeys: ['model.label', 'model.id', 'model.effortLevel'],
    terminal: { supported: true, configPath: 'display.showModel', upstreamItem: 'model' },
    desktop: { supported: true, componentHint: 'model chip', notes: 'Maps to the existing session model label when available.' },
  }),
  contextBar: item({
    id: 'contextBar',
    label: 'Context bar',
    category: 'core',
    kind: 'part',
    fieldKeys: ['context.usedPercent', 'context.remainingPercent'],
    terminal: { supported: true, configPath: 'display.showContextBar', upstreamItem: 'contextBar' },
    desktop: { supported: false, notes: 'Desktop needs a compact meter component before enabling.' },
  }),
  contextValue: item({
    id: 'contextValue',
    label: 'Context value',
    category: 'core',
    kind: 'part',
    fieldKeys: ['context.usedTokens', 'context.usedPercent', 'context.windowSize'],
    terminal: { supported: true, configPath: 'display.contextValue', upstreamItem: 'contextValue' },
    desktop: { supported: true, componentHint: 'context chip', notes: 'Current desktop HUD already prefers K-token context labels.' },
  }),
  project: item({
    id: 'project',
    label: 'Project',
    category: 'project',
    kind: 'part',
    fieldKeys: ['session.projectSlug', 'session.projectDir'],
    terminal: { supported: true, configPath: 'display.showProject', upstreamItem: 'project' },
    desktop: { supported: true, componentHint: 'workspace identity' },
  }),
  git: item({
    id: 'git',
    label: 'Git',
    category: 'project',
    kind: 'part',
    fieldKeys: ['workspace.gitBranch', 'workspace.gitDirty', 'workspace.gitAhead', 'workspace.gitBehind'],
    terminal: { supported: true, configPath: 'gitStatus', upstreamItem: 'git' },
    desktop: { supported: true, componentHint: 'ticker/panel chip', notes: 'Bridge projects sanitized git summary for configurable desktop ticker/panel slots.' },
  }),
  addedDirs: item({
    id: 'addedDirs',
    label: 'Added dirs',
    category: 'project',
    kind: 'part',
    fieldKeys: ['workspace.addedDirSlugs', 'workspace.addedDirsOverflowCount'],
    terminal: { supported: true, configPath: 'display.showAddedDirs', upstreamItem: 'addedDirs' },
    desktop: { supported: true, componentHint: 'ticker/panel chip', notes: 'Bridge stores basename-only added dirs for configurable desktop slots.' },
  }),
  sessionTokens: item({
    id: 'sessionTokens',
    label: 'Session tokens',
    category: 'tokens',
    kind: 'line',
    fieldKeys: ['tokens.input', 'tokens.output', 'tokens.cacheCreationInput', 'tokens.cacheReadInput'],
    terminal: { supported: true, configPath: 'display.showSessionTokens', upstreamItem: 'sessionTokens' },
    desktop: { supported: true, componentHint: 'expanded session metrics', notes: 'Desktop has token fields, but no dedicated configurable row yet.' },
  }),
  usage: item({
    id: 'usage',
    label: 'Usage',
    category: 'resource',
    kind: 'line',
    fieldKeys: ['usage.fiveHourUsedPercent', 'usage.sevenDayUsedPercent'],
    terminal: { supported: true, configPath: 'display.showUsage', upstreamItem: 'usage' },
    desktop: { supported: true, componentHint: 'UsageView' },
  }),
  promptCache: item({
    id: 'promptCache',
    label: 'Prompt cache',
    category: 'resource',
    kind: 'line',
    fieldKeys: ['session.lastAssistantResponseAt'],
    terminal: { supported: true, configPath: 'display.showPromptCache', upstreamItem: 'promptCache' },
    desktop: { supported: false, notes: 'Prompt cache is not projected into desktop-safe state yet.' },
  }),
  memory: item({
    id: 'memory',
    label: 'Memory',
    category: 'resource',
    kind: 'line',
    fieldKeys: ['system.memoryUsedPercent'],
    terminal: { supported: true, configPath: 'display.showMemoryUsage', upstreamItem: 'memory' },
    desktop: { supported: false, notes: 'Memory provider not implemented in Claude HUD One yet.' },
  }),
  environment: item({
    id: 'environment',
    label: 'Environment',
    category: 'resource',
    kind: 'line',
    fieldKeys: ['system.claudeMdCount', 'system.rulesCount', 'system.mcpCount', 'system.hooksCount'],
    terminal: { supported: true, configPath: 'display.showEnvironment', upstreamItem: 'environment' },
    desktop: { supported: false, notes: 'Environment counts are planned for diagnostics projection.' },
  }),
  tools: item({
    id: 'tools',
    label: 'Tools',
    category: 'activity',
    kind: 'line',
    fieldKeys: ['activity.activeToolName', 'activity.toolsCount'],
    terminal: { supported: true, configPath: 'display.showTools', upstreamItem: 'tools' },
    desktop: { supported: true, componentHint: 'tool chip', notes: 'Uses sanitized hook tool names only.' },
  }),
  agents: item({
    id: 'agents',
    label: 'Agents',
    category: 'activity',
    kind: 'part',
    fieldKeys: ['activity.agentsCount', 'activity.agentsRunningCount'],
    terminal: { supported: true, configPath: 'display.showAgents', upstreamItem: 'agents' },
    desktop: { supported: true, componentHint: 'ticker/panel chip', notes: 'Shows sanitized aggregate/running counts when bridge provides them.' },
  }),
  todos: item({
    id: 'todos',
    label: 'Todos',
    category: 'activity',
    kind: 'line',
    fieldKeys: ['activity.todosCount', 'activity.todosActiveCount', 'activity.todosCompletedCount'],
    terminal: { supported: true, configPath: 'display.showTodos', upstreamItem: 'todos' },
    desktop: { supported: true, componentHint: 'ticker/panel chip', notes: 'Shows sanitized todo aggregate counts when bridge provides them.' },
  }),
  activity: item({
    id: 'activity',
    label: 'Activity',
    category: 'activity',
    kind: 'line',
    fieldKeys: ['session.activity', 'session.statusText', 'activity.activeToolName'],
    terminal: { supported: true, configPath: 'activityLine', upstreamItem: 'activity' },
    desktop: { supported: true, componentHint: 'session ticker' },
  }),
  sessionTime: item({
    id: 'sessionTime',
    label: 'Session time',
    category: 'time',
    kind: 'line',
    fieldKeys: ['session.startedAt', 'session.lastAssistantResponseAt'],
    terminal: { supported: true, configPath: 'display.showSessionStartDate/display.showLastResponseAt', upstreamItem: 'sessionTime' },
    desktop: { supported: false, notes: 'Time fields are not projected yet.' },
  }),
  customLine: item({
    id: 'customLine',
    label: 'Custom line',
    category: 'custom',
    kind: 'line',
    fieldKeys: ['config.customLine'],
    terminal: { supported: true, configPath: 'display.customLine', upstreamItem: 'customLine' },
    desktop: { supported: false, notes: 'Desktop custom text slots are planned.' },
  }),
  cost: item({
    id: 'cost',
    label: 'Cost',
    category: 'resource',
    kind: 'metric',
    fieldKeys: ['cost.totalUsd'],
    terminal: { supported: true, configPath: 'display.showCost', notes: 'HUD Plus exposes cost through display.showCost rather than a row item.' },
    desktop: { supported: true, componentHint: 'CostView' },
  }),
  duration: item({
    id: 'duration',
    label: 'Duration',
    category: 'time',
    kind: 'metric',
    fieldKeys: ['cost.totalDurationMs', 'cost.totalApiDurationMs'],
    terminal: { supported: true, configPath: 'display.showDuration' },
    desktop: { supported: false, notes: 'Duration chip is planned.' },
  }),
  speed: item({
    id: 'speed',
    label: 'Speed',
    category: 'resource',
    kind: 'metric',
    fieldKeys: ['session.outputSpeed'],
    terminal: { supported: true, configPath: 'display.showSpeed' },
    desktop: { supported: true, componentHint: 'ticker/panel chip', notes: 'Shows sanitized output token speed when available.' },
  }),
  outputStyle: item({
    id: 'outputStyle',
    label: 'Output style',
    category: 'resource',
    kind: 'metric',
    fieldKeys: ['model.outputStyle'],
    terminal: { supported: true, configPath: 'display.showOutputStyle' },
    desktop: { supported: false, notes: 'Available in bridge state; no desktop visual yet.' },
  }),
  claudeCodeVersion: item({
    id: 'claudeCodeVersion',
    label: 'Claude Code version',
    category: 'resource',
    kind: 'metric',
    fieldKeys: ['model.claudeCodeVersion'],
    terminal: { supported: true, configPath: 'display.showClaudeCodeVersion' },
    desktop: { supported: false, notes: 'Diagnostics projection planned.' },
  }),
  effortLevel: item({
    id: 'effortLevel',
    label: 'Effort level',
    category: 'core',
    kind: 'metric',
    fieldKeys: ['model.effortLevel', 'model.thinkingEnabled'],
    terminal: { supported: true, configPath: 'display.showEffortLevel' },
    desktop: { supported: true, componentHint: 'model chip', notes: 'Bridge already stores sanitized effort fields.' },
  }),
}

export const displayItemList = (): DisplayItemDefinition[] => Object.values(DISPLAY_ITEM_REGISTRY)
export const terminalDisplayItemIds = (): HudDisplayItemId[] => displayItemList().filter((item) => item.terminal.supported).map((item) => item.id)
export const desktopDisplayItemIds = (): HudDisplayItemId[] => displayItemList().filter((item) => item.desktop.supported).map((item) => item.id)
