import type { HudFieldSchema } from './types'

const option = (label: string, value: string | number | boolean) => ({ label, value })

const terminalSwitch = (key: string, label: string, defaultValue: boolean, advanced = false): HudFieldSchema => ({
  key: `terminalHud.display.${key}`,
  label,
  configPath: `terminalHud.display.${key}`,
  group: 'terminal',
  surface: 'terminal',
  ui: 'switch',
  defaultValue,
  advanced,
})

const terminalColor = (key: string, label: string, defaultValue: string): HudFieldSchema => ({
  key: `terminalHud.colors.${key}`,
  label,
  configPath: `terminalHud.colors.${key}`,
  group: 'terminal-colors',
  surface: 'terminal',
  ui: key === 'barFilled' || key === 'barEmpty' ? 'text' : 'color',
  defaultValue,
})

export const HUD_FIELD_SCHEMA: HudFieldSchema[] = [
  {
    key: 'terminalHud.enabled',
    label: 'Terminal HUD enabled',
    description: 'Enable the built-in Claude HUD Plus compatible terminal statusLine renderer.',
    configPath: 'terminalHud.enabled',
    group: 'terminal',
    surface: 'terminal',
    ui: 'switch',
    defaultValue: true,
  },
  {
    key: 'terminalHud.preset',
    label: 'Terminal preset',
    configPath: 'terminalHud.preset',
    group: 'terminal',
    surface: 'terminal',
    ui: 'select',
    defaultValue: 'hud-plus-default',
    options: [
      option('HUD Plus default', 'hud-plus-default'),
      option('Minimal', 'minimal'),
      option('Custom', 'custom'),
    ],
  },
  {
    key: 'terminalHud.rows',
    label: 'Terminal rows',
    description: 'Configure ordered HUD Plus compatible row items.',
    configPath: 'terminalHud.rows',
    group: 'terminal-layout',
    surface: 'terminal',
    ui: 'row-builder',
    defaultValue: [
      ['model', 'contextBar', 'contextValue'],
      ['project', 'addedDirs', 'git'],
      ['sessionTokens'],
      ['activity'],
    ],
  },
  {
    key: 'terminalHud.rowOverflow',
    label: 'Row overflow',
    configPath: 'terminalHud.rowOverflow',
    group: 'terminal-layout',
    surface: 'terminal',
    ui: 'select',
    defaultValue: 'truncate',
    options: [option('Truncate', 'truncate'), option('Wrap', 'wrap')],
  },
  {
    key: 'terminalHud.maxWidth',
    label: 'Max terminal width',
    configPath: 'terminalHud.maxWidth',
    group: 'terminal-layout',
    surface: 'terminal',
    ui: 'number',
    defaultValue: null,
    advanced: true,
  },
  {
    key: 'terminalHud.showSeparators',
    label: 'Show separators',
    configPath: 'terminalHud.showSeparators',
    group: 'terminal-layout',
    surface: 'terminal',
    ui: 'switch',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'terminalHud.display.contextValue',
    label: 'Context value mode',
    configPath: 'terminalHud.display.contextValue',
    group: 'terminal-display',
    surface: 'terminal',
    ui: 'select',
    defaultValue: 'both',
    options: [
      option('Percent', 'percent'),
      option('Tokens', 'tokens'),
      option('Remaining', 'remaining'),
      option('Both', 'both'),
    ],
  },
  {
    key: 'terminalHud.display.usageValue',
    label: 'Usage value mode',
    configPath: 'terminalHud.display.usageValue',
    group: 'terminal-display',
    surface: 'terminal',
    ui: 'select',
    defaultValue: 'percent',
    options: [option('Percent', 'percent'), option('Remaining', 'remaining')],
  },
  terminalSwitch('showModel', 'Show model', true),
  terminalSwitch('showProject', 'Show project', true),
  terminalSwitch('showAddedDirs', 'Show added dirs', true),
  terminalSwitch('showContextBar', 'Show context bar', true),
  terminalSwitch('showSessionTokens', 'Show session tokens', true),
  terminalSwitch('showTokenBreakdown', 'Show token breakdown', true, true),
  terminalSwitch('showUsage', 'Show usage', false),
  terminalSwitch('usageBarEnabled', 'Show usage bar', true, true),
  terminalSwitch('showResetLabel', 'Show reset label', true, true),
  terminalSwitch('showTools', 'Show tools', true),
  terminalSwitch('showAgents', 'Show agents', true),
  terminalSwitch('showTodos', 'Show todos', true),
  terminalSwitch('showPromptCache', 'Show prompt cache', false),
  terminalSwitch('showMemoryUsage', 'Show memory usage', false, true),
  terminalSwitch('showEnvironment', 'Show environment counts', false, true),
  terminalSwitch('showCost', 'Show cost', false),
  terminalSwitch('showDuration', 'Show duration', false),
  terminalSwitch('showSpeed', 'Show speed', false),
  terminalSwitch('showOutputStyle', 'Show output style', false, true),
  terminalSwitch('showSessionName', 'Show session name', false, true),
  terminalSwitch('showClaudeCodeVersion', 'Show Claude Code version', false, true),
  terminalSwitch('showEffortLevel', 'Show effort level', false),
  terminalSwitch('showSessionStartDate', 'Show session start', false),
  terminalSwitch('showLastResponseAt', 'Show last response', false),
  terminalSwitch('showConfigCounts', 'Show config counts', false, true),
  terminalSwitch('usageCompact', 'Compact usage', false, true),
  {
    key: 'terminalHud.pathLevels',
    label: 'Project path levels',
    configPath: 'terminalHud.pathLevels',
    group: 'terminal-layout',
    surface: 'terminal',
    ui: 'select',
    defaultValue: 1,
    options: [option('1', 1), option('2', 2), option('3', 3)],
    advanced: true,
  },
  {
    key: 'terminalHud.activityLine.mode',
    label: 'Activity line mode',
    configPath: 'terminalHud.activityLine.mode',
    group: 'terminal-activity',
    surface: 'terminal',
    ui: 'select',
    defaultValue: 'auto',
    options: [option('Auto', 'auto'), option('Details', 'details'), option('Summary', 'summary')],
  },
  {
    key: 'terminalHud.activityLine.toolNameFormat',
    label: 'Tool name format',
    configPath: 'terminalHud.activityLine.toolNameFormat',
    group: 'terminal-activity',
    surface: 'terminal',
    ui: 'select',
    defaultValue: 'short',
    options: [option('Short', 'short'), option('Full', 'full')],
    advanced: true,
  },
  {
    key: 'terminalHud.display.addedDirsLayout',
    label: 'Added dirs layout',
    configPath: 'terminalHud.display.addedDirsLayout',
    group: 'terminal-display',
    surface: 'terminal',
    ui: 'select',
    defaultValue: 'inline',
    options: [option('Inline', 'inline'), option('Line', 'line')],
  },
  {
    key: 'terminalHud.display.modelFormat',
    label: 'Model format',
    configPath: 'terminalHud.display.modelFormat',
    group: 'terminal-display',
    surface: 'terminal',
    ui: 'select',
    defaultValue: 'full',
    options: [option('Full', 'full'), option('Compact', 'compact'), option('Short', 'short')],
  },
  {
    key: 'terminalHud.display.timeFormat',
    label: 'Time format',
    configPath: 'terminalHud.display.timeFormat',
    group: 'terminal-display',
    surface: 'terminal',
    ui: 'select',
    defaultValue: 'relative',
    options: [option('Relative', 'relative'), option('Absolute', 'absolute'), option('Both', 'both')],
  },
  {
    key: 'terminalHud.gitStatus.enabled',
    label: 'Git status enabled',
    configPath: 'terminalHud.gitStatus.enabled',
    group: 'terminal-git',
    surface: 'terminal',
    ui: 'switch',
    defaultValue: true,
  },
  {
    key: 'terminalHud.gitStatus.showAheadBehind',
    label: 'Show git ahead/behind',
    configPath: 'terminalHud.gitStatus.showAheadBehind',
    group: 'terminal-git',
    surface: 'terminal',
    ui: 'switch',
    defaultValue: false,
    advanced: true,
  },
  {
    key: 'terminalHud.display.customLine',
    label: 'Custom line',
    configPath: 'terminalHud.display.customLine',
    group: 'terminal-display',
    surface: 'terminal',
    ui: 'text',
    defaultValue: '',
    advanced: true,
  },
  terminalColor('model', 'Model color', '#38BDF8'),
  terminalColor('project', 'Project color', '#FBBF24'),
  terminalColor('context', 'Context color', '#22D3EE'),
  terminalColor('usage', 'Usage color', 'brightBlue'),
  terminalColor('usageWarning', 'Usage warning color', 'brightMagenta'),
  terminalColor('warning', 'Warning color', '#F59E0B'),
  terminalColor('critical', 'Critical color', '#F43F5E'),
  terminalColor('git', 'Git color', '#C084FC'),
  terminalColor('gitBranch', 'Git branch color', '#22D3EE'),
  terminalColor('label', 'Label color', 'dim'),
  terminalColor('labelTitle', 'Label title color', 'dim'),
  terminalColor('labelValue', 'Label value color', 'dim'),
  terminalColor('custom', 'Custom line color', '208'),
  terminalColor('barFilled', 'Bar filled character', '█'),
  terminalColor('barEmpty', 'Bar empty character', '░'),
  {
    key: 'terminalHud.json',
    label: 'Terminal JSON editor',
    configPath: 'terminalHud',
    group: 'terminal-advanced',
    surface: 'terminal',
    ui: 'json',
    advanced: true,
  },
  {
    key: 'desktopHud.enabled',
    label: 'Desktop HUD enabled',
    description: 'Enable configurable desktop HUD items for compact, peek, and expanded surfaces.',
    configPath: 'desktopHud.enabled',
    group: 'desktop',
    surface: 'desktop',
    ui: 'switch',
    defaultValue: true,
  },
  {
    key: 'desktopHud.preset',
    label: 'Desktop preset',
    configPath: 'desktopHud.preset',
    group: 'desktop',
    surface: 'desktop',
    ui: 'select',
    defaultValue: 'one-default',
    options: [
      option('One default', 'one-default'),
      option('Terminal parity', 'terminal-parity'),
      option('Custom', 'custom'),
    ],
  },
  {
    key: 'desktopHud.defaultPage',
    label: 'Default expanded page',
    configPath: 'desktopHud.defaultPage',
    group: 'desktop',
    surface: 'desktop',
    ui: 'select',
    defaultValue: 'usage',
    options: [option('Usage', 'usage'), option('Cost', 'cost'), option('Overview', 'overview')],
  },
  {
    key: 'desktopHud.visibleItems',
    label: 'Desktop visible items',
    configPath: 'desktopHud.visibleItems',
    group: 'desktop',
    surface: 'desktop',
    ui: 'json',
    defaultValue: {},
    advanced: true,
  },
]

export const fieldSchemaByGroup = (group: string): HudFieldSchema[] => HUD_FIELD_SCHEMA.filter((field) => field.group === group)
export const fieldSchemaBySurface = (surface: 'terminal' | 'desktop'): HudFieldSchema[] => HUD_FIELD_SCHEMA.filter((field) => field.surface === surface || field.surface === 'both')
